/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herencia;

/**
 *
 * @author gab-uwu
 */
public class app extends javax.swing.JFrame {

    /**
     * Creates new form app
     */
    public app() {
        initComponents();
        this.setLocationRelativeTo(null);
        resultado ventana = new resultado(this, true);
        TextPrompt num1 = new TextPrompt("Numero 1 (entero)", jTextFieldNumero1);
        TextPrompt num2 = new TextPrompt("Numero 2 (entero)", jTextFieldNumero2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextFieldNumero2 = new javax.swing.JTextField();
        jTextFieldNumero1 = new javax.swing.JTextField();
        jButtonRaices = new javax.swing.JButton();
        jButtonPotencias = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButtonDivison = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        JButtonSuma = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setAlignmentY(0.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 70, 30));
        getContentPane().add(jTextFieldNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 300, 40));

        jTextFieldNumero1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNumero1.setName(""); // NOI18N
        jTextFieldNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 300, 40));

        jButtonRaices.setBackground(new java.awt.Color(255, 133, 0));
        jButtonRaices.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonRaices.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRaices.setText("RAICES");
        jButtonRaices.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRaices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaicesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRaices, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 360, 40));

        jButtonPotencias.setBackground(new java.awt.Color(255, 133, 0));
        jButtonPotencias.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonPotencias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPotencias.setText("POTENCIAS");
        jButtonPotencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonPotencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPotencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 360, 40));

        jButtonMult.setBackground(new java.awt.Color(255, 133, 0));
        jButtonMult.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonMult.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMult.setText("MULTIPLICACION");
        jButtonMult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 40));

        jButtonDivison.setBackground(new java.awt.Color(255, 133, 0));
        jButtonDivison.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonDivison.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivison.setText("DIVISION");
        jButtonDivison.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonDivison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisonActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivison, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 360, 40));

        jButtonResta.setBackground(new java.awt.Color(255, 133, 0));
        jButtonResta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonResta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonResta.setText("RESTA");
        jButtonResta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 360, 40));

        JButtonSuma.setBackground(new java.awt.Color(255, 133, 0));
        JButtonSuma.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        JButtonSuma.setForeground(new java.awt.Color(255, 255, 255));
        JButtonSuma.setText("SUMA");
        JButtonSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, 40));

        jLabel4.setFont(new java.awt.Font("Source Code Pro", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATEMATICAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 60));

        jLabel3.setFont(new java.awt.Font("Source Code Pro", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BASICAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 60));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/calculator.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 70, 80));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/blue_grandient.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSumaActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaSumar suma = new HijaSumar();

        int a = Integer.parseInt(jTextFieldNumero1.getText());
        int b = Integer.parseInt(jTextFieldNumero2.getText());

        suma.setSuma(a, b);
        ventana.jLabel1.setText(suma.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_JButtonSumaActionPerformed

    private void jButtonPotenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciasActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaPotencia potencia = new HijaPotencia();

        int a = Integer.parseInt(jTextFieldNumero1.getText());
        int b = Integer.parseInt(jTextFieldNumero2.getText());

        potencia.setPotencia(a, b);
        ventana.jLabel1.setText(potencia.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonPotenciasActionPerformed

    private void jButtonRaicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaicesActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaRaiz raiz = new HijaRaiz();

        double a = Double.parseDouble(jTextFieldNumero1.getText());
        double b = Double.parseDouble(jTextFieldNumero2.getText());

        raiz.setRaiz(a, b);
        ventana.jLabel1.setText(raiz.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonRaicesActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaMul mul = new HijaMul();

        double a = Double.parseDouble(jTextFieldNumero1.getText());
        double b = Double.parseDouble(jTextFieldNumero2.getText());

        mul.setMul(a, b);
        ventana.jLabel1.setText(mul.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaRestar resta = new HijaRestar();

        double a = Double.parseDouble(jTextFieldNumero1.getText());
        double b = Double.parseDouble(jTextFieldNumero2.getText());

        resta.setResta(a, b);
        ventana.jLabel1.setText(resta.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonDivisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisonActionPerformed
        // TODO add your handling code here:
        resultado ventana = new resultado(this, true);
        HijaDivision division = new HijaDivision();

        double a = Double.parseDouble(jTextFieldNumero1.getText());
        double b = Double.parseDouble(jTextFieldNumero2.getText());

        division.setDivision(a, b);
        ventana.jLabel1.setText(division.setResul());
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonDivisonActionPerformed

    private void jTextFieldNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumero1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSuma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDivison;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonPotencias;
    private javax.swing.JButton jButtonRaices;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldNumero1;
    private javax.swing.JTextField jTextFieldNumero2;
    // End of variables declaration//GEN-END:variables
}
